---
- name: "Deploy batch {{ batch_number }} helm charts"
  debug:
    msg: "Deploying batch {{ batch_number }} with {{ charts_in_batch | length }} charts in parallel"

- name: "Deploy helm charts in batch {{ batch_number }} (without namespace) - async"
  command: >
    helm upgrade --install {{ item.name }} {{ item.repo }}
    {{ item.options | default('') }}
    --create-namespace
  with_items: "{{ charts_in_batch }}"
  async: 600  # 10 minutes timeout for each chart
  poll: 0     # Don't wait, start all in parallel
  environment: '{{ env_kc }}'
  when:
    - item.namespace is not defined or item.namespace == ""
  register: helm_jobs_no_ns

- name: "Deploy helm charts in batch {{ batch_number }} (with namespace) - async"
  command: >
    helm upgrade --install {{ item.name }} {{ item.repo }}
    --namespace {{ item.namespace }}
    {{ item.options | default('') }}
    --create-namespace
  with_items: "{{ charts_in_batch }}"
  async: 600  # 10 minutes timeout for each chart
  poll: 0     # Don't wait, start all in parallel
  environment: '{{ env_kc }}'
  when:
    - item.namespace is defined
    - item.namespace != ""
  register: helm_jobs_with_ns

- name: "Wait for all helm charts in batch {{ batch_number }} to complete"
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: helm_result_no_ns
  until: helm_result_no_ns.finished
  retries: 120  # 10 minutes total (120 * 5 seconds)
  delay: 5
  with_items: "{{ helm_jobs_no_ns.results | default([]) }}"
  when:
    - helm_jobs_no_ns is defined
    - helm_jobs_no_ns.results is defined
    - item.ansible_job_id is defined
  changed_when: '"deployed" in helm_result_no_ns.stdout'

- name: "Wait for all helm charts with namespace in batch {{ batch_number }} to complete"
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: helm_result_with_ns
  until: helm_result_with_ns.finished
  retries: 120  # 10 minutes total (120 * 5 seconds)
  delay: 5
  with_items: "{{ helm_jobs_with_ns.results | default([]) }}"
  when:
    - helm_jobs_with_ns is defined
    - helm_jobs_with_ns.results is defined
    - item.ansible_job_id is defined
  changed_when: '"deployed" in helm_result_with_ns.stdout'

- name: "Display completion status for batch {{ batch_number }}"
  debug:
    msg: "All {{ charts_in_batch | length }} charts in batch {{ batch_number }} have been deployed"

- name: "CALICO BLOCK - after batch {{ batch_number }} when tigera-operator in charts_in_batch"
  when: '"tigera-operator" in (charts_in_batch | map(attribute="namespace") | list)'
  block:

  - name: Calico - Wait few seconds for deployments to start - wait to make sure calico-node is getting started - required for containerd...
    pause: seconds=10
    changed_when: false

  - name: Wait for calico-node daemonset to be ready
    shell: kubectl -n calico-system get daemonset calico-node -o jsonpath='{.status.numberReady}/{.status.desiredNumberScheduled}'
    environment: '{{ env_kc }}'
    register: calico_node_ready
    until: calico_node_ready.stdout.split('/')[0] == calico_node_ready.stdout.split('/')[1] and calico_node_ready.stdout.split('/')[0] | int > 0
    retries: 60
    delay: 10
    ignore_errors: true

  - name: Calico - Restart containerd due to containerd cni bugs are still there in containerd 1.6.6
    systemd: name=containerd state=restarted enabled=yes daemon_reload=yes

  - name: Calico - Wait few seconds for containerd to restart
    pause: seconds=10
    changed_when: false

  - name: Wait for CoreDNS deployment to be ready
    shell: kubectl -n kube-system get deployment coredns -o jsonpath='{.status.readyReplicas}'
    environment: '{{ env_kc }}'
    register: coredns_ready
    until: coredns_ready.stdout | int > 0
    retries: 20
    delay: 10
    ignore_errors: false
    changed_when: false

  - debug:
      msg: "Calico networking components are ready, proceeding to next batch"
