---
- hosts: master
  become: yes
  become_method: sudo
  tags:
  - helm
  tasks:

  - set_fact:
      env_kc: '{{ proxy_env |default({}) | combine ({"PATH" : "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin"  }) | combine ({"KUBECONFIG" :"/etc/kubernetes/admin.conf"}) }}'
    tags:
    - always
  
  - name: 'Download {{ helm.install_script_url }}'
    environment: '{{ proxy_env | default ({}) }}'
    get_url: url={{ helm.install_script_url | default ("") }} dest=/tmp/helm_install_script force=yes mode="0755"
    when: helm.install_script_url is defined
    tags:
    - helm

  - name: Run /tmp/helm_install_script
    environment: '{{env_kc}}'
    shell: "/tmp/helm_install_script --version {{helm.helm_version | default ('latest')}}"
    register: command_result
    changed_when: '"is up-to-date" not in command_result.stdout'
    when: helm.install_script_url is defined
    args:
      chdir: /tmp/
    tags:
    - helm

  - name: helm completion shell
    environment: '{{env_kc}}'
    shell: helm completion {{ shell | default ('bash') }} > ~/.kube/helm_completion.bash.inc
    args:
      warn: no
    tags:
    - helm

  - name: helm completion to ~/.bash_profile
    lineinfile:
      dest: ~/.bash_profile
      line: '[[ -x ${HOME}/.kube/helm_completion.bash.inc ]] && source ${HOME}/.kube/helm_completion.bash.inc'
      state: present
    when: shell is undefined or shell == 'bash'
    tags:
    - helm

  - name: helm remove/cleanup
    environment: '{{env_kc}}'
    shell: ( helm reset || true ) && ( kubectl delete deployment --namespace=kube-system tiller-deploy || true ) && ( kubectl delete service --namespace=kube-system tiller-deploy  || true ) && (  kubectl delete clusterrolebinding tiller  || true ) && (  kubectl delete --namespace=kube-system sa tiller )
    tags:
    - helm_reset
    - helm
    ignore_errors: yes

  - name: create helm related RBAC (tiller sa)
    environment: '{{env_kc}}'
    shell: kubectl --namespace=kube-system create sa tiller
    tags:
    - helm
    - rbac

  - name: create helm related RBAC (tiller clusterrolebinding)
    environment: '{{env_kc}}'
    shell: kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
    tags:
    - helm
    - rbac

  - name: helm init
    environment: '{{env_kc}}'
    shell: "helm init --host {{ inventory_hostname }}:6443 "
    when: helm.install_script_url is defined
    register: command_result
    changed_when: "'Tiller is already installed' not in command_result.stdout"
    args:
      chdir: /root/
    tags:
    - helm

  - name: helm sanity - wait for tiller pod to be running
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
    shell: "kubectl get --namespace kube-system pods | tail -n +2 | grep -w 'tiller-deploy' | grep -v -w 'Running' || true "
    register: command_result
    tags:
    - sanity_helm
    - sanity
    - helm
    until: command_result.stdout == ""
    retries: 50
    delay: 3

  - name: create helm related RBAC (Patch Tiller s Deployment to use the new ServiceAccount)
    environment: '{{env_kc}}'
    shell: 'kubectl -n kube-system patch deploy/tiller-deploy -p ''{"spec": {"template": {"spec": {"serviceAccountName": "tiller"}}}}'''
    register: command_result
    changed_when: '"not patched" not in command_result.stdout'
    tags:
    - helm
    - rbac

  - name: Update helm Tiller
    environment: '{{env_kc}}'
    command: helm init --upgrade
    when: helm is defined
    tags:
    - helm

  - name: helm repo add 
    environment: '{{env_kc}}'
    command: helm repo add {{ item.name }} {{ item.url }}
    with_items: 
      - '{{ helm.repos | default("") }}'
    when: helm.repos is defined
    tags:
    - helm

  - name: helm repo update #Sometimes initial repo add corrupts the repo and update fixes it.
    environment: '{{env_kc}}'
    command: helm repo update
    when: helm is defined
    tags:
    - helm

  - name: Wait few seconds for tiller deployment to start
    pause: seconds=3
    tags:
    - helm

  - name: helm sanity - wait for tiller pod to be running
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
    shell: "kubectl get --namespace kube-system pods | tail -n +2 | grep -w 'tiller-deploy' | grep -v -w 'Running' || true "
    register: command_result
    #failed_when: '"/" in command_result.stdout'
    tags:
    - sanity_helm
    - sanity
    - helm
    until: command_result.stdout == ""
    retries: 30
    delay: 3

  - name: Wait few seconds to be 100% tiller deployment is up (the above is not enough)
    pause: seconds=10
    tags:
    - helm

  - name: helm charts/packages deployment
    environment: '{{env_kc}}'
    command: 'helm install {{ item.repo }} --namespace {{ item.namespace | default("default") }} --name {{ item.name }} {{ item.options | default ("") }}'
    with_items: 
      - "{{ helm.packages_list }}"
    when: helm.packages_list is defined
    tags:
    - helm
    - charts_deploy

  - name: Wait few seconds for deployments to start
    pause: seconds=3
    tags:
    - helm
    - charts_deploy


  - name: helm full sanity - wait for all installed charts to become running
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
    shell: "kubectl get --all-namespaces pods | tail -n +2 | grep -v -w 'Running' || true "
    register: command_result
    tags:
    - sanity_helm
    - sanity
    - helm
    - charts_deploy
    until: command_result.stdout == ""
    retries: 60
    delay: 3

