---
- set_fact:
    env_kc: '{{ {} | combine ({"PATH" : "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin/"  }) | combine ({"KUBECONFIG" :"/etc/kubernetes/admin.conf"}) }}'
  tags:
  - always

### Post install messages
- block:

# Too much clutter, so disabling get events
  # - name: Get events
  #   command: kubectl get events --all-namespaces
  #   register: command_result
  #   changed_when: false
  #   tags:
  #   - cluster_info
  #   - cluster_status

  # - name: Display events
  #   debug:
  #     var: command_result.stdout_lines
  #   changed_when: false
  #   tags:
  #   - cluster_info
  #   - cluster_status

  - name: Get deployed helm charts
    shell: "helm list --all-namespaces --all --superseded --pending"
    changed_when: false
    register: command_result
    tags:
    - cluster_status
    - helm
    - post_deploy

  - name: Print all helm charts
    debug:
      var: command_result.stdout_lines
    changed_when: false

  - name: Get pods
    command: "kubectl get pods -o wide --all-namespaces --show-labels=true --show-kind=true"
    register: command_result
    changed_when: false
    tags:
    - cluster_status

  - name: Display pods
    debug:
      var: command_result.stdout_lines
    changed_when: false
    tags:
    - cluster_status

  - name: Get pods not yet in Running status
    shell: "kubectl get --all-namespaces pods --no-headers | grep -v -w 'Running' || true "
    register: command_result
    changed_when: false

  - name: Print pods not yet in Running status
    debug:
      var: command_result.stdout_lines

  - name: Get nodes
    command: kubectl get nodes
    register: command_result
    changed_when: false

  - name: Display nodes
    debug:
      var: command_result.stdout_lines
    changed_when: false

  - name: Get cluster-info
    command: kubectl cluster-info
    register: command_result
    changed_when: false

  - name: cluster-info
    debug:
      #msg: "{{ command_result.stdout_lines | from_yaml }}"
      var: command_result.stdout_lines    
    changed_when: false

  - name: Print cluster information and other useful commands.
    vars:
      msg: |
           Your cluster should be up and running !
           Now you may:
           - type: alias to see the predefined aliases
           - for a command line "dashboard", on master type:
             - wp     # watch pods in all namespaces (optionally --show-labels )
             - kg po  # kg='kubectl get --all-namespaces -o wide' <po|ing|etc...>
             - ks     # ks='kubectl -n kube-system ' get po
           - k top node / pod # More tips: https://kubernetes.io/docs/user-guide/kubectl-cheatsheet/
           - to check pods which are not yet in Running status, run: "kubectl get --all-namespaces pods --no-headers | grep -v -w 'Running' "
           
           - browse your master (using fqdn) to see the dashboard:
             http://{{groups[cluster_inventory_group.masters][0]}}
               or, ideally (depending what was defined in config)
             http://dashboard.{{custom.networking.dnsDomain}} (when var custom.networking.dnsDomain properly defined and set in your dns )
    debug: var=msg
#     msg: "{{ msg.split('\n') }}"
    register: command_result
    changed_when: false
    #http://dashboard.{{ custom.networking.dnsDomain | default ("you may want to define custom.networking.dnsDomain") }}

#  - name: Print cluster information and other useful commands.
#    debug: vars=command_result
#    changed_when: false
  environment: '{{env_kc}}'
  tags:
  - cluster_info
  - postinstall_messages
  run_once: true
